const mongoose = require('mongoose')

const baseClassSchema = new mongoose.Schema({
    name: String,
	alignment: String,
	hitDie: String,
	startingWealth: String,
	classSkills: String,
	skillRanksPerLevel: String,
	level1BABAndSaves: String,
    level2BABAndSaves: String,
    level3BABAndSaves: String,
    level4BABAndSaves: String,
    level5BABAndSaves: String,
    level6BABAndSaves: String,
    level7BABAndSaves: String,
    level8BABAndSaves: String,
    level9BABAndSaves: String,
    level10BABAndSaves: String,
    level11BABAndSaves: String,
    level12BABAndSaves: String,
    level13BABAndSaves: String,
    level14BABAndSaves: String,
    level15BABAndSaves: String,
    level16BABAndSaves: String,
    level17BABAndSaves: String,
    level18BABAndSaves: String,
    level19BABAndSaves: String,
    level20BABAndSaves: String,
	spellsPerDayLevel1: String,
	spellsPerDayLevel2: String,
	spellsPerDayLevel3: String,
	spellsPerDayLevel4: String,
	spellsPerDayLevel5: String,
	spellsPerDayLevel6: String,
	spellsPerDayLevel7: String,
	spellsPerDayLevel8: String,
	spellsPerDayLevel9: String,
	spellsPerDayLevel10: String,
	spellsPerDayLevel11: String,
	spellsPerDayLevel12: String,
	spellsPerDayLevel13: String,
	spellsPerDayLevel14: String,
	spellsPerDayLevel15: String,
	spellsPerDayLevel16: String,
	spellsPerDayLevel17: String,
	spellsPerDayLevel18: String,
	spellsPerDayLevel19: String,
	spellsPerDayLevel20: String,
    spellsKnownLevel1: String,
	spellsKnownLevel2: String,
	spellsKnownLevel3: String,
	spellsKnownLevel4: String,
	spellsKnownLevel5: String,
	spellsKnownLevel6: String,
	spellsKnownLevel7: String,
	spellsKnownLevel8: String,
	spellsKnownLevel9: String,
	spellsKnownLevel10: String,
	spellsKnownLevel11: String,
	spellsKnownLevel12: String,
	spellsKnownLevel13: String,
	spellsKnownLevel14: String,
	spellsKnownLevel15: String,
	spellsKnownLevel16: String,
	spellsKnownLevel17: String,
	spellsKnownLevel18: String,
	spellsKnownLevel19: String,
	spellsKnownLevel20: String,
	weaponProficiency: String,
	armorProficiency: String,
    classAbility1: String,
    classAbility2: String,
    classAbility3: String,
    classAbility4: String,
    classAbility5: String,
    classAbility6: String,
    classAbility7: String,
    classAbility8: String,
    classAbility9: String,
    classAbility10: String,
	description: String,
	oathBreaking: String,
	source: String,
    image: String,
	notes: String

},
{
	timestamps:true
})

const BaseClass = mongoose.model('Base Class', baseClassSchema)

module.exports = BaseClass